-- -------------------------------------------------
-- Project Name: --------- New PostgreSQL Diagram --
-- Database: ------------- PostgreSQL --------------
-- Export Date: ---------- 2026-09-05 00:19 --------
-- Created By: ----------- dbdesign.io -------------
-- -------------------------------------------------

-- ---------- TABLE ACTIVOS -----------
CREATE TABLE IF NOT EXISTS Activos (
  id_activo                     int GENERATED BY DEFAULT AS IDENTITY,
  nombre                        varchar,
  id_estado_de_disponibilidad   int,
  id_ubicacion                  Espacio,
  id_tipo                       int,
  id_estado_fisico              int,
  
  CONSTRAINT pk_Activos PRIMARY KEY (id_activo)
);

-- ---------- TABLE ESPACIOS -----------
CREATE TABLE IF NOT EXISTS Espacios (
  id_espacio                    int GENERATED BY DEFAULT AS IDENTITY,
  nombre                        varchar,
  aforo_maximo                  int,
  id_estado_de_disponibilidad   int,
  id_ubicacion                  int,
  id_facultad                   int,
  
  CONSTRAINT pk_Espacios PRIMARY KEY (id_espacio)
);

-- ---------- TABLE ESTADOS_DE_DISPONIBILIDAD -----------
CREATE TABLE IF NOT EXISTS Estados_de_disponibilidad (
  id_estado_de_disponibilidad   int GENERATED BY DEFAULT AS IDENTITY,
  nombre                        varchar,
  descripcion                   varchar,
  
  CONSTRAINT pk_Estados_de_disponibilidad PRIMARY KEY (id_estado_de_disponibilidad)
);

-- ---------- TABLE CATEGORIAS_TIPOS -----------
CREATE TABLE IF NOT EXISTS Categorias_Tipos (
  id_tipo                   int GENERATED BY DEFAULT AS IDENTITY,
  nombre                    varchar,
  descripcion               varchar,
  plazo_maximo_devolucion   integer,
  
  CONSTRAINT pk_Categorias_Tipos PRIMARY KEY (id_tipo)
);

-- ---------- TABLE CATEGORIAS_ESTADOS_FISICOS -----------
CREATE TABLE IF NOT EXISTS Categorias_Estados_Fisicos (
  id_estado_fisico   int GENERATED BY DEFAULT AS IDENTITY,
  nombre             varchar,
  descripcion        varchar,
  
  CONSTRAINT pk_Categorias_Estados_Fisicos PRIMARY KEY (id_estado_fisico)
);

-- ---------- TABLE UBICACIONES_UNIVERSITARIAS -----------
CREATE TABLE IF NOT EXISTS Ubicaciones_Universitarias (
  id_ubicacion_universitaria   int GENERATED BY DEFAULT AS IDENTITY,
  nombre                       varchar,
  coordenadas                  varchar,
  
  CONSTRAINT pk_Ubicaciones_Universitarias PRIMARY KEY (id_ubicacion_universitaria)
);

-- ---------- TABLE FACULTAD -----------
CREATE TABLE IF NOT EXISTS Facultad (
  id_facultad   int GENERATED BY DEFAULT AS IDENTITY,
  nombre        varchar,
  
  CONSTRAINT pk_Facultad PRIMARY KEY (id_facultad)
);

-- ---------- FOREIGN KEYS -----------
ALTER TABLE Activos                    ADD CONSTRAINT fk_Activos_id_estado_de_disponibilidad FOREIGN KEY (id_estado_de_disponibilidad) REFERENCES Estados_de_disponibilidad(id_estado_de_disponibilidad);
ALTER TABLE Activos                    ADD CONSTRAINT fk_Activos_id_ubicacion FOREIGN KEY (id_ubicacion) REFERENCES Espacios(id_espacio);
ALTER TABLE Activos                    ADD CONSTRAINT fk_Activos_id_estado_fisico FOREIGN KEY (id_estado_fisico) REFERENCES Categorias_Estados_Fisicos(id_estado_fisico);
ALTER TABLE Espacios                   ADD CONSTRAINT fk_Espacios_id_estado_de_disponibilidad FOREIGN KEY (id_estado_de_disponibilidad) REFERENCES Estados_de_disponibilidad(id_estado_de_disponibilidad);
ALTER TABLE Espacios                   ADD CONSTRAINT fk_Espacios_id_facultad FOREIGN KEY (id_facultad) REFERENCES Facultad(id_facultad);
ALTER TABLE Categorias_Tipos           ADD CONSTRAINT fk_Categorias_Tipos_id_tipo FOREIGN KEY (id_tipo) REFERENCES Activos(id_tipo);
ALTER TABLE Ubicaciones_Universitarias ADD CONSTRAINT fk_Ubicaciones_Universitarias_id_ubicacion_universitaria FOREIGN KEY (id_ubicacion_universitaria) REFERENCES Espacios(id_ubicacion);